class MoviesConstants:
    MOVIE_NAMES = [
        "The Shawshank Redemption",
        "The Godfather",
        "The Dark Knight",
        "Pulp Fiction",
        "Schindler's List",
        "The Lord of the Rings: The Return of the King",
        "12 Angry Men",
        "The Good, the Bad and the Ugly",
        "Forrest Gump",
        "Inception",
        "The Matrix",
        "Star Wars: Episode V - The Empire Strikes Back",
        "The Silence of the Lambs",
        "The Green Mile",
        "Goodfellas",
        "Fight Club",
        "The Lord of the Rings: The Fellowship of the Ring",
        "The Lord of the Rings: The Two Towers",
        "The Godfather: Part II",
        "The Matrix",
        "City of God",
        "Se7en",
        "Life Is Beautiful",
        "The Usual Suspects",
        "Léon: The Professional",
        "Saving Private Ryan",
        "Interstellar",
        "The Pianist",
        "The Departed",
        "Gladiator",
        "The Prestige",
        "The Lion King",
        "Back to the Future",
        "The Intouchables",
        "The Terminator",
        "Whiplash",
        "American History X",
        "The Shining",
        "The Sixth Sense",
        "The Grand Budapest Hotel",
        "Django Unchained",
        "The Truman Show",
        "The Dark Knight Rises",
        "The Lives of Others",
        "The Revenant",
        "Jurassic Park",
        "The Godfather: Part III",
        "The Lord of the Rings: The Return of the King",
        "A Beautiful Mind",
        "The Pursuit of Happyness",
        "The Wolf of Wall Street",
        "Harry Potter and the Sorcerer's Stone",
        "Harry Potter and the Deathly Hallows: Part 2",
        "Harry Potter and the Prisoner of Azkaban",
        "Harry Potter and the Goblet of Fire",
        "Harry Potter and the Chamber of Secrets",
        "Harry Potter and the Deathly Hallows: Part 1",
        "Harry Potter and the Order of the Phoenix",
        "Harry Potter and the Half-Blood Prince",
        "The Avengers",
        "Avengers: Infinity War",
        "Avengers: Endgame",
        "The Dark Knight",
        "The Godfather",
        "Schindler's List",
        "The Lord of the Rings: The Return of the King",
        "Pulp Fiction",
        "The Good, the Bad and the Ugly",
        "Fight Club",
        "Forrest Gump",
        "Inception",
        "The Lord of the Rings: The Fellowship of the Ring",
        "The Lord of the Rings: The Two Towers",
        "The Matrix",
        "Goodfellas",
        "Star Wars: Episode V - The Empire Strikes Back",
        "One Flew Over the Cuckoo's Nest",
        "Seven Samurai",
        "Se7en",
        "City of God",
        "Life Is Beautiful",
        "The Silence of the Lambs",
        "It's a Wonderful Life",
        "The Usual Suspects",
        "Léon: The Professional",
        "Spirited Away",
        "Saving Private Ryan",
        "Interstellar",
        "The Green Mile",
        "The Godfather: Part II",
        "The Shawshank Redemption",
        "The Departed",
        "The Pianist",
        "Gladiator",
        "The Prestige",
        "The Lion King",
        "Apocalypse Now",
        "Back to the Future",
        "The Terminator",
        "Alien",
        "Whiplash",
        "American History X",
        "The Shining",
        "The Sixth Sense",
        "The Grand Budapest Hotel",
        "Django Unchained",
        "The Truman Show",
        "The Dark Knight Rises",
        "The Lives of Others",
        "The Revenant",
        "Jurassic Park",
        "The Godfather: Part III",
        "A Beautiful Mind",
        "The Pursuit of Happyness",
        "The Wolf of Wall Street",
    ]

    TAGS = [
        "Drama",
        "Crime",
        "Thriller",
        "Classic",
        "Academy Award Winner",
        "Action",
        "Adventure",
        "Fantasy",
        "Sci-Fi",
        "Historical",
        "Biography",
        "War",
        "Mystery",
        "Suspense",
        "Romance",
        "Animation",
        "Comedy",
        "Horror",
        "Cult Classic",
        "Independent",
        "Epic",
        "Psychological",
        "Mind-bending",
        "Heartwarming",
        "Gripping",
        "Iconic",
        "Inspirational",
        "Memorable",
        "Visually Stunning",
        "Emotional",
        "Intense",
        "Critically Acclaimed",
        "Oscar Winner",
        "Golden Globe Winner",
        "Cannes Film Festival Winner",
        "Palme d'Or Winner",
        "Cult Favorite",
        "Timeless",
        "Blockbuster",
        "Masterpiece",
        "Award-Winning",
        "Groundbreaking",
        "Unforgettable",
        "Heroic",
        "Dark",
        "Powerful",
        "Thought-Provoking",
        "Enigmatic",
        "Surreal",
        "Action-packed",
        "Entertaining",
        "Enthralling",
        "Must-Watch",
        "Legendary",
        "Quotable",
        "Twist Ending",
        "Iconic Characters",
        "Historically Significant",
        "Oscar-nominated",
        "Golden Globe-nominated",
        "Critically Acclaimed",
        "Academy Award-winning Director",
        "Cinematic",
        "Cerebral",
        "Classic Storytelling",
        "Cinematography",
        "Character-driven",
        "Unpredictable",
        "Iconic Scenes",
        "Multi-Award Winner",
        "Epic Scale",
        "Timeless Appeal",
        "Genre-defining",
        "Spectacular",
        "Immersive",
        "Impactful",
        "Groundbreaking Visual Effects",
        "Riveting",
        "Oscar-nominated Performances",
        "Golden Globe-nominated Performances",
        "Cannes Film Festival Nominee",
        "Critics' Choice",
        "Audience Favorite",
        "Box Office Hit",
        "Beloved Characters",
        "Epic Journey",
        "Masterful Direction",
        "Award-Winning Performances",
        "Deeply Moving",
        "Nostalgic",
        "Edge-of-your-seat",
        "Unconventional",
        "Cinematic Experience",
        "Artistic",
        "Stunning Soundtrack",
        "Compelling Story"
    ]